/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 2323037ab535eb7bee95b3fcb5368faa)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		CACHE: KVNamespace;
		R2: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
		RESEND_API_KEY: string;
	}
}
interface Env extends Cloudflare.Env {}
