/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 2323037ab535eb7bee95b3fcb5368faa)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/worker");
  }
  interface Env {
    CACHE: KVNamespace;
    R2: R2Bucket;
    DB: D1Database;
    ASSETS: Fetcher;
    RESEND_API_KEY: string;
    CACHE_TTL_SECONDS: string;
    CACHE_STALE_WHILE_REVALIDATE_SECONDS: string;
    RATE_LIMIT_AUTH_MAX: string;
    RATE_LIMIT_CONTACT_MAX: string;
    RATE_LIMIT_GUESTBOOK_MAX: string;
    RATE_LIMIT_UPLOAD_MAX: string;
  }
}
interface Env extends Cloudflare.Env {}
