DELETE FROM events;
DELETE FROM videos;
DELETE FROM publications;
DELETE FROM guestbook;

-- All 51 events from original site (sorted by date DESC)
INSERT INTO events (title, image, location, description, date, time, price, is_past, details_link, reservation_link) VALUES
-- Future events
('Thé Dansant 2026', '/images/events/evt010226.png', 'Espace JMP, Sucy-en-Brie', 'Organisé en partenariat avec la ville de Sucy-en-Brie pour un moment dansant et festif avec toujours 2 orchestres aux styles différents et complémentaires pour mieux vous ravir. Au programme, l''Harmonie et ses 30 musiciens ainsi que le Picotango Orquesta, spécialisé dans le tango argentin.', '2026-02-01', '14H', '15-25€', 0, '/the-dansant', 'https://www.helloasso.com/associations/les-amis-de-l-harmonie/evenements/the-dansant-2026-sucy-en-brie'),

-- Past events (2025)
('Banquet de l''amitié', '/images/events/evt291125.png', 'Espace JMP', 'Profitez de ce moment convivial agrémenté d''un repas et d''un spectacle, l''Harmonie Municipale sera présente comme chaque année ! Les banquets de l''Amitié, sont organisés pour les seniors de 65 ans et plus. Evènement organisé par la Maison des Seniors de Sucy-en-Brie.', '2025-11-30', '11H30', 'Gratuit', 1, NULL, NULL),
('Banquet de l''amitié', '/images/events/evt231125.png', 'Espace JMP', 'Profitez de ce moment convivial agrémenté d''un repas et d''un spectacle, l''Harmonie Municipale sera présente comme chaque année ! Les banquets de l''Amitié, sont organisés pour les seniors de 65 ans et plus. Evènement organisé par la Maison des Seniors de Sucy-en-Brie.', '2025-11-29', '11H30', 'Gratuit', 1, NULL, NULL),
('Banquet de l''amitié', '/images/events/evt221125.png', 'Espace JMP', 'Profitez de ce moment convivial agrémenté d''un repas et d''un spectacle, l''Harmonie Municipale sera présente comme chaque année ! Les banquets de l''Amitié, sont organisés pour les seniors de 65 ans et plus. Evènement organisé par la Maison des Seniors de Sucy-en-Brie.', '2025-11-23', '11H30', 'Gratuit', 1, NULL, NULL),
('Cérémonie du 11 novembre', '/images/events/evt111123.jpg', 'Parvis de l''église Saint-Martin, Sucy-en-Brie', 'Commémoration de l''Armistice de 1918 et de tous les morts pour la France.', '2025-11-11', '11H', 'Gratuit', 1, NULL, NULL),
('Centenaire d''une Sucycienne', '/images/events/evt111025.png', 'Sucy-en-Brie', 'L''Harmonie Municipale participera aux 100 ans d''une Sucycienne ! L''Harmonie Municipale aura le plaisir de prendre part à un événement rare et émouvant : le centenaire d''une habitante de Sucy. Parce que la musique saura toujours rassembler les générations et accompagner les grands moments de la vie, nous serons présents pour offrir une touche musicale à cette célébration unique. Un rendez-vous que nous ne voudrions manquer sous aucun prétexte !', '2025-10-11', '13H15', 'Privé', 1, NULL, NULL),
('Sortie ''John Williams, du classique au cinéma''', '/images/events/evt280925.png', 'La Seine Musicale, Boulogne', 'COMPLET - Nous vous proposons d''aller ensemble à la Seine Musicale pour un concert fantastique autour de John Williams. De Star Wars à E.T. en passant par les mélodies ensorcelantes d''Harry Potter, John Williams a transformé la musique de film en une véritable symphonie, puisant son inspiration chez les grands compositeurs classiques.', '2025-09-28', '16H', '38€', 1, NULL, NULL),
('Brocante de Sucy', '/images/events/evt210925.png', 'Centre ville, Sucy-en-Brie', 'Un incontournable de notre rentrée : la brocante de Sucy-en-Brie ! Nous déambulerons dans les allées du Centre Ville, sur des rythmes festifs !', '2025-09-21', '10H', 'Gratuit', 1, NULL, NULL),
('Assemblée générale ordinaire', '/images/events/evt080925.png', 'Maison des association, Sucy-en-Brie', 'L''AGO permettra de faire le bilan du premier semestre de l''année 2025, d''approuver les comptes, de fixer les orientations pour l''année à venir, et de renouveler le conseil d''administration. L''AGO est réservée aux adhérents 2025-2026 de l''association.', '2025-09-08', '18H30', 'Gratuit', 1, NULL, NULL),
('Fête des associations', '/images/events/evt070925.png', 'Espace JMP, Sucy-en-Brie', 'Profitez du concert de l''Harmonie Municipale de Sucy-en-Brie et venez nous rencontrer sur notre stand.', '2025-09-07', '09H30', 'Gratuit', 1, NULL, NULL),
('Barbecue de fin d''année', '/images/events/evt2806251.png', 'Salle de la tête de cheval, Sucy-en-Brie', 'Réservé aux adhérents et aux musiciens. On clôture l''année musicale par notre traditionnel BBQ ! Venez nombreux pour ce moment de partage ! Chacun apporte ce qu''il souhaite.', '2025-06-28', '18H', 'Gratuit', 1, NULL, NULL),
('Concert Résidence des Cèdres', '/images/events/evt280625.png', 'Résidence des Cèdres, Sucy-en-Brie', 'Comme chaque année nous viendrons animer le goûter de nos ainés, avec un petit concert festif pour clôturer cette belle saison musicale.', '2025-06-28', '15h', 'Gratuit', 1, NULL, NULL),
('Fête de la Musique', '/images/events/evt220624.jpg', 'Ferme du Grand-Val', 'L''Harmonie sortira pour l''occasion son répertoire festif ! Venez nombreux !', '2025-06-21', '18h', 'Gratuit', 1, NULL, NULL),
('Commémoration du 18 juin 1940', '/images/events/evt180624.jpg', 'Esplanade Château Montaleau, Sucy-en-Brie', 'Alors en déplacement à Londres et refusant la défaite de la France, le Général de Gaulle prend la parole sur la radio britannique, la BBC, et lance son célèbre appel à poursuivre le combat pour une France Libre : « Quoi qu''il arrive, la flamme de la résistance ne doit pas s''éteindre et ne s''éteindra pas »', '2025-06-18', '19H', 'Gratuit', 1, NULL, NULL),
('Bal traditionnel', '/images/events/evt150625.png', 'Gloriette, Parc des Sports, Sucy-en-Brie', 'Venez danser ! 3 orchestres rien que pour vous, Korr an Noz, l''Ensemble instrumental d''Agnès Friberg et l''Harmonie Municipale de Sucy-en-Brie, dans un joli cadre verdoyant !', '2025-06-15', '15h', 'Gratuit', 1, NULL, NULL),
('Commémoration du 8 mai 1945', '/images/events/evt080524.jpg', 'Parvis église Saint-Martin, Sucy-en-Brie', 'Jeudi 8 mai se tiendra la cérémonie du 80e anniversaire de la Victoire du 8 mai 1945.', '2025-05-08', '11H', 'Gratuit', 1, NULL, NULL),
('Répétition ouverte', '/images/events/evt110425.png', 'Conservatoire, Sucy-en-Brie', 'Plongez dans les coulisses de la musique ! L''Harmonie Municipale de Sucy-en-Brie vous ouvre les portes de sa répétition ! Venez vivre un moment unique et découvrir comment se prépare un concert, dans une ambiance conviviale et passionnée.', '2025-04-11', '20h', 'Gratuit', 1, NULL, NULL),
('Concert Club de rugby Sucy', '/images/events/evt070424.jpg', 'Stade de rugby, Sucy-en-Brie', 'Nous serons auprès du club de rugby de Sucy-en-Brie afin de les soutenir en musique !', '2025-04-06', 'A définir', 'Gratuit', 1, NULL, NULL),
('Concert Résidence de la Cité Verte', '/images/events/evt2903252.png', 'Résidence de la Cité Verte, Sucy-en-Brie', 'Comme chaque année nous viendrons animer le goûter de nos ainés, avec un petit concert festif.', '2025-03-29', '16h', 'Gratuit', 1, NULL, NULL),
('Carnaval', '/images/events/evt290325.png', 'Parvis de l''école de la Cité Verte, Sucy-en-Brie', 'Déambulation musicale, avec la Batucada de l''Harmonie Municipale + concert de l''orchestre. Rejoignez-nous pour un moment festif !', '2025-03-29', '15h', 'Gratuit', 1, NULL, NULL),
('Sortie ''Ennio Morricone et le cinéma Italien''', '/images/events/evt260316.png', 'La Seine Musicale, Boulogne', 'Nous vous proposons d''aller ensemble à la Seine Musicale pour un concert fantastique autour d''Ennio Morricone et du cinéma Italien. ''Il était une fois dans l''Ouest'', ''Le Bon, la Brute et le Truand'' , ''Pour une poignée de dollars'', ''Le Parrain'', ''Le Clan des Siciliens''... Inscription en ligne jusqu''au 27 septembre. Réservé aux adhérents 2024-2025.', '2025-03-16', '16H', '30€', 1, NULL, NULL),
('Fête de la Saint-Vincent', '/images/events/evt210124.jpg', 'Espace JMP, Sucy-en-Brie', 'Depuis le Moyen-Age, chaque 22 janvier, vignerons, famille, voisins, amis parfois venus de loin, participent aux festivités organisées pour célébrer la Saint-Vincent.', '2025-02-09', '12H15', 'Privé', 1, NULL, NULL),
('Thé Dansant 2025', '/images/events/evt260125.png', 'Espace JMP, Sucy-en-Brie', 'Organisé en partenariat avec la ville de Sucy-en-Brie pour un moment dansant et festif avec toujours 2 orchestres aux styles différents et complémentaires pour mieux vous ravir. Au programme, l''Harmonie et ses 30 musiciens ainsi que le Picotango Orquesta, spécialisé dans le tango argentin.', '2025-01-26', '14H', '15-25€', 1, '/the-dansant', 'https://www.helloasso.com/associations/les-amis-de-l-harmonie/evenements/the-dansant-2025-sucy'),

-- Past events (2024)
('Cinéma ''En Fanfare''', '/images/events/evt211224.png', 'Cinéma, Sucy-en-Brie', 'Thibaut est un chef d''orchestre de renommée internationale qui parcourt le monde. Lorsqu''il apprend qu''il a été adopté, il découvre l''existence d''un frère, Jimmy, employé de cantine scolaire et qui joue du trombone dans une fanfare du nord de la France. En apparence tout les sépare, sauf l''amour de la musique.', '2024-12-21', '21H', '2€', 1, NULL, NULL),
('Banquet de l''amitié', '/images/events/evt191123.jpg', 'Espace JMP', 'Profitez de ce moment convivial agrémenté d''un repas et d''un spectacle, l''Harmonie Municipale sera présente comme chaque année ! Les banquets de l''Amitié, sont organisés pour les seniors de 65 ans et plus. Evènement organisé par la Maison des Seniors de Sucy-en-Brie.', '2024-12-01', '11H30', 'Gratuit', 1, NULL, 'https://www.ville-sucy.fr/banquet2024'),
('Cérémonie du 11 novembre', '/images/events/evt111123.jpg', 'Parvis de l''église Saint-Martin, Sucy-en-Brie', 'Commémoration de l''Armistice de 1918 et de tous les morts pour la France.', '2024-11-11', '11H', 'Gratuit', 1, NULL, NULL),
('Concert Rencontre d''Harmonies', '/images/events/evt091124.jpg', 'Espace JMP, Sucy-en-Brie', 'Les Amis de l''Harmonie en partenariat avec la Confédération Musicale de France (94) et la Ville de Sucy-en-Brie vous proposent une journée musicale dédiée aux orchestres d''harmonie. Pour l''occasion l''Harmonie Municipale de Sucy-en-Brie qui fêtera en 2027 ses 160 ans, accueillent l''Espérance Brévannaise et l''Harmonie du Conservatoire de Neuilly-sur-Marne. Au programme, 3 heures de musique et un final regroupant les 100 musiciens sur scène.', '2024-11-09', '14H', 'Gratuit', 1, NULL, NULL),
('Brocante de Sucy', '/images/events/evt170923.jpg', 'Centre ville, Sucy-en-Brie', 'Un incontournable de notre rentrée : la brocante de Sucy-en-Brie ! Nous déambulerons dans les allées du Centre Ville, sur des rythmes festifs !', '2024-09-15', '10H', 'Gratuit', 1, NULL, NULL),
('Fête des associations', '/images/events/evt080924.png', 'Gymnase Montaleau, Sucy-en-Brie', 'Profitez du concert de l''Harmonie Municipale de Sucy-en-Brie et venez nous rencontrer sur notre stand.', '2024-09-08', '09H', 'Gratuit', 1, NULL, NULL),
('Passage de la flamme Paralympique', '/images/events/evt270824.png', 'Château de Sucy-en-Brie', 'Du 25 au 28 août, la Flamme Paralympique, portée par près de 1000 éclaireurs, traversera une cinquantaine de villes dont deux dans le Val-de-Marne : Sucy et Valenton. Juste avant de finir son aventure à Paris pour la cérémonie d''ouverture des premiers jeux paralympiques d''été en France, le 28 août.', '2024-08-27', '9H', 'Gratuit', 1, NULL, NULL),
('Fête de la Musique', '/images/events/evt220624.jpg', 'Centre culturel, Sucy-en-Brie', 'C''est maintenant un incontournable, la Ferme de Grand-Val a le plaisir de vous accueillir pour la Fête de la Musique. L''Harmonie sortira pour l''occasion son répertoire festif ! Venez nombreux !', '2024-06-22', '19h30', 'Gratuit', 1, NULL, NULL),
('Commémoration du 18 juin 1940', '/images/events/evt180624.jpg', 'Esplanade Château Montaleau, Sucy-en-Brie', 'Alors en déplacement à Londres et refusant la défaite de la France, le Général de Gaulle prend la parole sur la radio britannique, la BBC, et lance son célèbre appel à poursuivre le combat pour une France Libre : « Quoi qu''il arrive, la flamme de la résistance ne doit pas s''éteindre et ne s''éteindra pas »', '2024-06-18', '19H', 'Gratuit', 1, NULL, NULL),
('Concert sport et musique', '/images/events/evt150624.jpg', 'Parc Omnisport, Sucy-en-Brie', 'Animation musicale dans le cadre de la manifestation "Je cours pour la culture"', '2024-06-15', '14H30', 'Gratuit', 1, NULL, NULL),
('Les trésors insolites du Musée', '/images/events/evt090624.png', 'Musée de la Musique, Philarmonie de Paris', 'Nous vous proposons une sortie au Musée de la Musique (Philarmonie de Paris). Durant la visite (environ 1h30), un conférencier-musicologue vous guidera parmi une sélection de ses chefs-d''œuvre favoris. Il vous fera (re)découvrir les détails insolites d''instruments connus ou moins connus et vous révèlera leurs savoureux secrets.', '2024-06-09', '13H', '10€', 1, NULL, 'https://www.helloasso.com/associations/les-amis-de-l-harmonie/evenements/musee-de-la-musique-09-juin-2024'),
('Un dimanche en Fauré', '/images/events/evt020624.jpg', 'Espace JMP, Sucy-en-Brie', 'Une journée pour célébrer la musique française de Gabriel Fauré aux couleurs subtiles et fascinantes, empreinte de poésie et de spiritualité.', '2024-06-02', '15H', 'Gratuit', 1, NULL, NULL),
('Commémoration du 8 mai 1945', '/images/events/evt080524.jpg', 'Parvis église Saint-Martin, Sucy-en-Brie', 'Mercredi 8 mai se tiendra la cérémonie du 79e anniversaire de la Victoire du 8 mai 1945.', '2024-05-08', '11H', 'Gratuit', 1, NULL, NULL),
('Concert fermeture des Sister Cities Games', '/images/events/evt010524.jpg', 'Stade C.Arron, Sucy-en-brie', 'Sur la vague des JO Paris 2024, la Ville de Sucy-en-Brie organise les Sister Cities Games. Une rencontre sportive internationale entre les jeunes de Sucy et ceux de ses villes jumelles et villes amies autour de 4 sports olympiques.', '2024-05-05', '17H', 'Gratuit', 1, NULL, NULL),
('Concert ouverture des Sister Cities Games', '/images/events/evt010524.jpg', 'Stade C.Arron, Sucy-en-brie', 'Sur la vague des JO Paris 2024, la Ville de Sucy-en-Brie organise les Sister Cities Games. Une rencontre sportive internationale entre les jeunes de Sucy et ceux de ses villes jumelles et villes amies autour de 4 sports olympiques.', '2024-05-01', '17H', 'Gratuit', 1, NULL, NULL),
('Cérémonie de la déportation', '/images/events/evt240424.jpg', 'Place de l''Église, Sucy-en-Brie', 'Le dernier dimanche d''avril est chaque année dédié à la célébration de la mémoire des victimes de la déportation dans les camps de concentration et d''extermination nazis lors la seconde guerre mondiale.', '2024-04-28', '12H', 'Gratuit', 1, NULL, NULL),
('Concert à la Résidence de la Cité Verte', '/images/events/evt2303241.jpg', 'Maison de retraite de la Cité Verte, Sucy-en-Brie', 'C''est aussi cela la mission de l''Harmonie Municipale, faire plaisir à tous les publics !', '2024-03-23', 'A définir', 'Gratuit', 1, NULL, NULL),
('Concert au Rond d''or', '/images/events/evt230324.jpg', 'Rond d''or, Sucy-en-Brie', 'Déambulation musicale au Rond d''or de la Cité Verte de Sucy-en-Brie. Rejoignez-nous pour un moment festif !', '2024-03-23', 'A définir', 'Gratuit', 1, NULL, NULL),
('Cérémonie des accords d''évian', '/images/events/evt190324.jpg', 'Sucy-en-Brie', 'La journée nationale du souvenir et de recueillement à la mémoire des victimes civiles et militaires de la guerre d''Algérie et des combats en Tunisie et au Maroc a lieu le 19 mars.', '2024-03-19', 'A définir', 'Gratuit', 1, NULL, NULL),
('Le concert impromptu', '/images/events/evt020324.jpg', 'L''Orangerie, Sucy-en-Brie', 'En première partie du Concert impromptu venez découvrir la restitution du travail de l''Harmonie Municipale après une Master classe, véritable co-création autour d''une approche contemporaine qui met en relief les synergies possibles entre les différents langages artistiques..', '2024-03-02', '20H30', '7-11€', 1, NULL, 'https://www.vostickets.net/billet?id=SUCY_EN_BRIE'),
('Thé Dansant', '/images/events/evt280124.jpg', 'Espace JMP, Sucy-en-Brie', 'Nous vous proposons un rendez-vous musical haut en couleur avec 2 orchestres complémentaires dans la grande tradition de la Coupole à Paris. Plus de 4h de musique non-stop !', '2024-01-28', '14H', '10-20€', 1, '/the-dansant', 'https://www.helloasso.com/associations/les-amis-de-l-harmonie/evenements/the-dansant-2024-2'),
('Nuit des Conservatoires', '/images/events/evt260124.jpg', 'Conservatoire, Sucy-en-Brie', 'A partir de 17h30 venez découvrir au conservatoire les différentes pratiques musicales et artistiques ! Et dès 21H assistez à notre répétition.', '2024-01-26', '17H30 - 22H', 'Gratuit', 1, NULL, NULL),
('Fête de la Saint-Vincent', '/images/events/evt210124.jpg', 'Espace JMP, Sucy-en-Brie', 'Depuis le Moyen-Age, chaque 22 janvier, vignerons, famille, voisins, amis parfois venus de loin, participent aux festivités organisées pour célébrer la Saint-Vincent.', '2024-01-21', '12H15', 'Privé', 1, NULL, NULL),

-- Past events (2023)
('Concert Musiques Traditionnelles', '/images/events/evt251123.jpg', 'La Grange, Sucy-en-Brie', 'C''est par un voyage «insensé» du soleil de mediterranée au soleil levant, en passant par l''Inde, la Chine et quelques contrées américaines où l''on aime le jazz et les big bands que l''harmonie vous convie.', '2023-11-25', '15H', '10€', 1, NULL, 'https://www.helloasso.com/associations/les-amis-de-l-harmonie/evenements/concert-musiques-traditionnelles'),
('Banquet de l''amitié', '/images/events/evt191123.jpg', 'JMP, Sucy-en-Brie', 'Profitez de ce moment convivial agrémenté d''un repas et d''un spectacle, l''Harmonie Municipale sera présente comme chaque année ! Les banquets de l''Amitié, sont organisés pour les seniors de 65 ans et plus. Evènement organisé par la Maison des Seniors de Sucy-en-Brie.', '2023-11-26', '12H', 'Gratuit', 1, NULL, 'https://www.ville-sucy.fr/agenda/banquet-de-lamitie-2023-inscriptions-en-ligne'),
('Cérémonie du 11 novembre', '/images/events/evt111123.jpg', 'Parvis de l''église Saint-Martin, Sucy-en-Brie', 'Commémoration de l''Armistice de 1918 et de tous les morts pour la France.', '2023-11-11', '11H', 'Gratuit', 1, NULL, NULL),
('Brocante de Sucy', '/images/events/evt170923.jpg', 'Sucy-en-Brie', 'L''Harmonie Municipale de Sucy-en-Brie déambulera à travers la brocante pour vous faire danser !', '2023-09-17', 'A définir', 'Gratuit', 1, NULL, NULL),
('Fête des associations', '/images/events/evt100923.jpg', 'Gymnase Montaleau, Sucy-en-Brie', 'Profitez du concert de l''Harmonie Municipale de Sucy-en-Brie et venez nous rencontrer sur notre stand.', '2023-09-10', '10H', 'Gratuit', 1, NULL, NULL);

-- All 20 videos
INSERT INTO videos (title, youtube_id) VALUES
('Bamboléooooo !', 'n13yE9CTxYU'),
('Thé Dansant 2025', 'iZwfSjflbKA'),
('Passage de la Flamme Paralympique', 'dF3qZQ9EZxw'),
('Fête de la musique 2024', 'LUJZmqu1RhU'),
('Un dimanche en Fauré - Pavane & Pie Jesu', 'BJ6ZsHqiZnQ'),
('Cérémonie d''ouverture des Sister Cities Games 2024', '1PtbOEhup-E'),
('Virgule Musicale - Le Concert Impromptu', 'L0YjfpQzHXI'),
('Thé Dansant 2024', 'ze4b6Br0qCI'),
('Concert "Musiques Traditionnelles"', 'JKdJ5Ia9YZk'),
('Commémoration de l''Armistice de 1918 - 11 novembre 2023', 'YbWBx3DkJrU'),
('Brocante de Sucy-en-Brie 2023', 'MJSRTO9_66c'),
('Fête des associations de Sucy-en-Brie 2023', 'jg0jYA1mtq4'),
('Concert pour la délégation de Para Athlétisme des USA', 'gKQQWB8-PvQ'),
('Fête de la musique 2023', 'RS7MAwTtdZE'),
('Concert au Popott'' Truck 2023', 'ZzvzJ3wVxgQ'),
('Commémoration du 8 mai 1945', 'dwMtHfKVsKY'),
('Thé Dansant 2023', 'z2hks6eO8WQ'),
('Fête de la Saint-Vincent 2023', 'U-SYrUB8kEw'),
('"The Best Of Beatles"', '5ouK1KDKNF0'),
('Concert "Autour de la Méditerranée"', 'XOiG6ri3xRw');

-- All 188 publications (Instagram post IDs extracted from URLs)
INSERT INTO publications (instagram_post_id) VALUES
('DSSKC1CCBKx'),
('DSP5Z-QiHsL'),
('DSK0eP1iITT'),
('DRrvkoeiPD_'),
('DRpbunliFTR'),
('DRZurybiCMY'),
('DQ9De2xiAEr'),
('DQ6zPCliN7P'),
('DQ1EJ9QiGtK'),
('DQmX2uliD1O'),
('DQWZIdZCEyS'),
('DQMpJxDCB2U'),
('DP8jVZOiKTo'),
('DP6MMrVCCM9'),
('DPrTV7UiO4Q'),
('DPJ3VJNCEHp'),
('DO_OtS7iPKt'),
('DOiEeNlCL2o'),
('DOOE-dbCB4-'),
('DNQDdsgIeYB'),
('DM9nW6eI9UJ'),
('DMrrqEtI3ZY'),
('DL17lk0InOI'),
('DLj6Dtqobsj'),
('DLef4ewIw4h'),
('DLQJQaFor9-'),
('DLNfeudI_Y_'),
('DLMnhu0IRzA'),
('DLFBnxwIFEQ'),
('DLC1t5Bolw8'),
('DLApCbqo0cd'),
('DKhras1Iamo'),
('DKbUo12IrTy'),
('DKWmMkYoEYN'),
('DJoU8XqiBJn'),
('DJhGqdHixkb'),
('DJZzruGChTB'),
('DJPPg15C8Ip'),
('DIoS3tniJ03'),
('DIiuyQgi7FW'),
('DIY8sC3CSMC'),
('DIQ3_ZSi9DF'),
('DIJ0_IoCMHy'),
('DH3w6hsiqbn'),
('DH3wKxPi-jV'),
('DHt1gEMubJB'),
('DHrPf_tuFA4'),
('DHRZejHuWTS'),
('DDNB5DwIOmc'),
('DG51a8_CpCP'),
('DFUsidOOmRR'),
('FTjKnutWgF'),
('DErd0nAuQ0A'),
('DDPkRzIIXyT'),
('DCoXzw7u4Ok'),
('DDIaZruOlRC'),
('DDC6vidO9Jl'),
('DCymb5quVNP'),
('DCwyIgRO8tS'),
('DDAea2cOJVK'),
('DCPMijrNYGC'),
('DCMh2Yool8c'),
('DBtkB55CTgH'),
('DBjeEN6CdZJ'),
('DAx2qhwukjR'),
('DAT0M6Ju41I'),
('DAJQzEZoPV2'),
('DAB5n8oOz3I'),
('C_950S0twSG'),
('C_8nrX3OYuh'),
('C_sOgCmo0wr'),
('C_aXVWFo-xd'),
('C_OCFVMCpu0'),
('C_M9MD3twXh'),
('C-gFiFYOix9'),
('C-c23t5iUmN'),
('C-SwMc6Iwla'),
('C-F85vghGoH'),
('C94bxq_vLeZ'),
('C92vicRsK55'),
('C9rfaBtuQOR'),
('C9mTSQQBo8A'),
('C9ZUgVRBRyT'),
('C81uJAFIGuj'),
('C8y0bdlP5PX'),
('C8iaRIHIznX'),
('C8cCkU4iE0Y'),
('C8aXZBPCNT-'),
('C8Y9mCzNFBh'),
('C8XOvP6KJw-'),
('C8FNNmePT1z'),
('C8FNJ4Fv66i'),
('C8Cr7X5ImwR'),
('C8ASHHqiGiM'),
('C79lqUPCXx0'),
('C7zpKZyO1Rl'),
('C7vtE05ig93'),
('C7lu7g2Ckli'),
('C7e44UAin7h'),
('C7blTd-idPJ'),
('C7CTIlGi3oq'),
('C6t7gQvLlMc'),
('C6YyT2bCAtG'),
('C45jz3zoXau'),
('C4pR8nEovq0'),
('C4DdSGcrT32'),
('C4ANOisLacM'),
('C33KonorsV9'),
('C32-mdGrlig'),
('C3UwbYNNznX'),
('C299_jhIYBg'),
('C298OeJIpGS'),
('C2zBjmArIfJ'),
('C2r94ZboHEu'),
('C2hR_ckLVNq'),
('C2chL8ENre4'),
('C2Zb_cPrl9U'),
('C2R5lfGrOFW'),
('C0mj0ShrL8j'),
('C2K6iqfr_M5'),
('C2NieG7LoQ9'),
('C0HtGvRLBDA'),
('CxYrqbDLrHR'),
('CxAh25SLN0V'),
('CyS-dq-rop-'),
('CwXH8OtL5d4'),
('CwQNzZOIF0N'),
('Cvz36rbIq34'),
('Cvz3FOyI2O2'),
('Cvy9JNgI-wX'),
('CuT-KbprU3g'),
('CtXHh52rKQU'),
('CtM68dDoC6K'),
('Cs-1hHCLGbW'),
('CsyGThwI6he'),
('CsotcQ_Lt-g'),
('CsJEkyttntD'),
('CqQx6ShDqbY'),
('Cpu4l89jH7E'),
('CpRxTXhDtr1'),
('Co4nNY2jnuP'),
('CnwpeDcIOO4'),
('CnfBMjGLPGR'),
('CmXNSGaL9o9'),
('Clbqh6CDez1'),
('ClL31YBDfcb'),
('ClLL0qcjfgR'),
('ClI1CWKIHkV'),
('Ck2xpAEjARo'),
('Ck0_-ngjgbT'),
('Ck0_ZnfDq_j'),
('Ck0gSF0DB-e'),
('CkiUf1njKMx'),
('CkOG4bYDYB8'),
('Cj3J2u5DGk_'),
('Ci7U0DajErk'),
('CivXQGara_e'),
('Cf_EWL9j2li'),
('CfyoaOjDuXa'),
('CfmghsvIrij'),
('CfiiG5YjEJk'),
('Cfa2hFzjMfl'),
('CfYRwZPjN3m'),
('CfUAL5UDK7l'),
('CfTH9hWj-3F'),
('CfSWRfKjxJv'),
('CfN7tnYjZgS'),
('CfMMbKNDm6Z'),
('Ce_-devoSR8'),
('Ce_zbz0LO0y'),
('Ce9aYeIqreX'),
('CexiktkjU_8'),
('CevTAUaLUVt'),
('Cean5LVDwvU'),
('CeWngjIrvii'),
('CdVeUNLjhGX'),
('CYLfCDBDdh1'),
('CXdrXX1Ieve'),
('CXNw1QEIp_Z'),
('CXF6S5ioOSg'),
('CW0jlU1IKYC'),
('CW0ec_Eobv2'),
('CW0S_CSoOMl'),
('CW0LJLOolL2'),
('CWyZIBvIMWn'),
('CWyYSvAoP5u');

-- Guestbook entries
INSERT INTO guestbook (first_name, last_name, message, date) VALUES
('Geneviève', 'Fraïoli', 'Nous avons été sous le charme le 26 janvier 2025 avec une ambiance simple et pleine de vie
Bravo aux orchestres et danseurs
Merci à tous', '2025-02-02'),
('Priyanka', 'DILIPE', 'Incroyable concert ce samedi 09 novembre!! Merci infiniment à vous pour ce moment et BRAVO :))', '2024-11-11'),
('Catherine ', 'CASSIER', 'Bravo pour cette belle prestation et pour l''organisation de ce concert du samedi 9 novembre. Nous avons apprécié les 3 harmonies successives puis assemblées.
Habitués de l''harmonie de Sucy, la prestation de ce jour était de haute qualité. On sentait qu''il y avait beaucoup de travail en amont. Nos oreilles vous remercient infiniment.', '2024-11-10'),
('Muriel ', 'Bouché', 'Beaucoup de répétitions et d''investissement et le résultat est là !
Bravo à tous continuez.', '2024-02-14'),
('Tiu', 'Elena-Daniela', 'Une vraie réussite le thé dansant dans une ambiance conviviale et familiale.
Nos enfants de 8 et 11 ans ont beaucoup apprécié ce moment.
À refaire.', '2024-02-11'),
('Guitton ', 'Annick', 'Excellent après-midi dansant. Nous avons apprécié les nouvelles interprétations de l''harmonie municipale.', '2024-02-08'),
('Goncalves', 'Helder', 'Danser sur les musiques de 30 musiciens et Picotango , c''est la classe !!!
L''accueil, l''organisation , l''agencement de cette belle salle parquetée : c''était parfait.
Monsieur le Chef d''Orchestre a de l''humour pour donner une bonne ambiance !', '2024-02-07'),
('Soka', 'Daniel', 'Très bien', '2024-02-07');
